// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CarsDataClearerML.Model
{
    public class ModelInput
    {
        [ColumnName("Brand"), LoadColumn(0)]
        public string Brand { get; set; }


        [ColumnName("Model"), LoadColumn(1)]
        public string Model { get; set; }


        [ColumnName("Category"), LoadColumn(2)]
        public string Category { get; set; }


        [ColumnName("MonthsSinceManufacturing"), LoadColumn(3)]
        public float MonthsSinceManufacturing { get; set; }


        [ColumnName("EngineType"), LoadColumn(4)]
        public string EngineType { get; set; }


        [ColumnName("Power"), LoadColumn(5)]
        public float Power { get; set; }


        [ColumnName("Shifter"), LoadColumn(6)]
        public string Shifter { get; set; }


        [ColumnName("DistanceTravelled"), LoadColumn(7)]
        public float DistanceTravelled { get; set; }


        [ColumnName("Въздушни възглавници - Предни"), LoadColumn(8)]
        public float Въздушни_възглавници___Предни { get; set; }


        [ColumnName("Бордкомпютър"), LoadColumn(9)]
        public float Бордкомпютър { get; set; }


        [ColumnName("Бързи бавни скорости"), LoadColumn(10)]
        public float Бързи_бавни_скорости { get; set; }


        [ColumnName("Климатик"), LoadColumn(11)]
        public float Климатик { get; set; }


        [ColumnName("Климатроник"), LoadColumn(12)]
        public float Климатроник { get; set; }


        [ColumnName("4x4"), LoadColumn(13)]
        public float _4x4 { get; set; }


        [ColumnName("7 места"), LoadColumn(14)]
        public float _7_места { get; set; }


        [ColumnName("Газова уредба"), LoadColumn(15)]
        public float Газова_уредба { get; set; }


        [ColumnName("Метанова уредба"), LoadColumn(16)]
        public float Метанова_уредба { get; set; }


        [ColumnName("С регистрация"), LoadColumn(17)]
        public float С_регистрация { get; set; }


        [ColumnName("2(3) Врати"), LoadColumn(18)]
        public float _2_3__Врати { get; set; }


        [ColumnName("4(5) Врати"), LoadColumn(19)]
        public float _4_5__Врати { get; set; }


        [ColumnName("Панорамен люк"), LoadColumn(20)]
        public float Панорамен_люк { get; set; }


        [ColumnName("Теглич"), LoadColumn(21)]
        public float Теглич { get; set; }


        [ColumnName("Аларма"), LoadColumn(22)]
        public float Аларма { get; set; }


        [ColumnName("Кожен салон"), LoadColumn(23)]
        public float Кожен_салон { get; set; }


        [ColumnName("Десен волан"), LoadColumn(24)]
        public float Десен_волан { get; set; }


        [ColumnName("Price"), LoadColumn(25)]
        public float Price { get; set; }


    }
}
